name: practice
description: "Practice Page module."
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^3.0.0-dev.16
  flutter_hooks: ^0.21.2

  riverpod_annotation: ^3.0.0-dev.16
  carousel_slider: ^5.1.1

  # Local packages
  core:
    path: ../../core
  metronome:
    path: ../../features/metronome
  chord_progression:
    path: ../../features/chord_progression

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  build_runner: ^2.4.12
  freezed: ^3.0.6
  mockito: ^5.4.6

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.kktaro.practice
    iosBundleIdentifier: com.kktaro.practice

resolution: workspace
