targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/{{file}}.dart': 'lib/generated/{{file}}.g.dart'
      freezed:
        options:
          build_extensions:
            "^lib/src/{{}}.dart": "lib/generated/{{}}.freezed.dart"
