name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read Flutter version from .fvmrc
      id: fvm-config
      uses: kuhnroyal/flutter-fvm-config-action@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config.outputs.flutter-version }}
        channel: 'stable'
        cache: true

    - name: Verify Flutter installation
      run: flutter doctor -v

    - name: Install Melos
      run: dart pub global activate melos

    - name: Bootstrap project
      run: melos bs

    - name: Check formatting
      run: melos run format

    - name: Run static analysis
      run: melos run lint

    - name: Run tests
      run: melos run test

    - name: Check for uncommitted changes
      run: |
        if ! git diff --exit-code; then
          echo "❌ Code generation or formatting created uncommitted changes"
          echo "Please run 'melos run generate' and 'melos run format' locally and commit the changes"
          exit 1
        fi
